version: "3"
services:
    aurora4x-docker:
        container_name: ${COMPOSE_PROJECT_NAME}_game
        volumes:
            - /dev/shm:/dev/shm
            - /volume1/aurora4x/saves/${saveslot}/AuroraDB.db:/root/AuroraDB.db # use variable saveslot to change active save
            - /volume1/aurora4x/ssl/:/config/ssl
        ports:
          - 6000:3000 # HTTP
          - 6443:3001 # HTTPS
        environment:
          CUSTOM-USER: avalon 
          PASSWORD: changeme # Basic auth password
          TITLE: Aurora4X Web
        image: ghcr.io/firefly2442/aurora4x-docker